#version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
      - DB_HOST=ep-morning-mountain-a2pbo4v1.eu-central-1.pg.koyeb.app
      - DB_PORT=5432
      - DB_DATABASE=job_lister
      - DB_USERNAME=job_lister_user
      - DB_PASSWORD=StD7qazTTeoWy21VlJnU3qeSrm8dJcp9
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: job_lister
      POSTGRES_USER: job_lister_user
      POSTGRES_PASSWORD: StD7qazTTeoWy21VlJnU3qeSrm8dJcp9
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
